application: librarylookup-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /.*
  script: librarylookup.application