application: librarylookup
version: 2
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /admin/.*
  script: librarylookup.py
  login: admin

- url: /.*
  script: librarylookup.py

